AllCops:
  NewCops: disable

Lint/MissingCopEnableDirective:
  Enabled: false

Metrics/ClassLength:
  Max: 1000
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
